In [27]:
import pandas as pd
import ollama
import re

In [9]:
prova_2015 = pd.read_csv("prova_2015.csv")
anos = prova_2015['Ano'].unique()
print(anos)
prova_2015.head()

[2015]

,Nquestao,enunciado,A,B,C,D,E,questao_completa,Ano,Aplicacao,gabarito
0,1,"Suponha que, entabulado contrato facultativo d...",O prazo prescricional anual é interrompido com...,O prazo prescricional anual é interrompido com...,O prazo prescricional trienal é suspenso com o...,O prazo prescricional anual é suspenso com o p...,"Na hipótese de resseguro, o prazo prescriciona...","Suponha que, entabulado contrato facultativo d...",2015,2,D
1,2,No que se refere ao contrato estimatório do Di...,"Pode ter por objeto bem fungível, e a restitui...","Os riscos são do consignante, que suporta a pe...","Após a entrega da coisa, a posse é exercida em...",O preço de estima é ato unilateral do consigna...,Em decorrência da natureza própria do contrato...,No que se refere ao contrato estimatório do Di...,2015,2,A
2,2,No que se refere ao contrato estimatório do Di...,"Pode ter por objeto bem fungível, e a restitui...","Os riscos são do consignante, que suporta a pe...","Após a entrega da coisa, a posse é exercida em...",O preço de estima é ato unilateral do consigna...,Em decorrência da natureza própria do contrato...,No que se refere ao contrato estimatório do Di...,2015,2,C
3,3,A respeito da hermenêutica e da aplicação do d...,Diante da existência de antinomia entre dois d...,"Os tradicionais critérios hierárquico, cronoló...",A técnica da subsunção é suficiente e adequada...,Diante da existência de antinomia entre dois d...,"A aplicação do princípio da especialidade, em ...",A respeito da hermenêutica e da aplicação do d...,2015,2,A
4,4,A respeito da locação dos imóveis urbanos da L...,"Conforme entendimento consolidado do STJ, o pr...",É assente na jurisprudência do STJ que a cláus...,"Nas locações comerciais, exige-se a anuência d...","Conforme entendimento do STF, a penhora de bem...","A responsabilidade dos fiadores, no caso de pr...",A respeito da locação dos imóveis urbanos da L...,2015,2,C

In [14]:
SYSTEM = (
    """Você é um especialista em Direito brasileiro resolvendo questões de 
    múltipla escolha de provas. Considere a legislação e a 
    jurisprudência brasileiras. Apenas uma alternativa está correta."""
)

TEMPLATE = """Responda a questão abaixo.

Enunciado: {enunciado}
Alternativas: {alternativas}

Responda apenas com a letra da alternativa correta, exatamente neste formato:
Resposta: <letra>"""

In [22]:
def montar_prompt(row, letras="ABCDE"):
    alts = "\n".join(f"{l}) {row[l]}" for l in letras if pd.notna(row.get(l)))
    return TEMPLATE.format(enunciado=row["enunciado"], alternativas=alts)

In [28]:
def extrair_letra(texto):
    achados = re.findall(r"Resposta:\s*\**\s*([A-E])", texto, flags=re.I)
    return achados[-1].upper() if achados else None

In [39]:
def usou_gpu(modelo):
    for m in ollama.ps().models:
        if m.model == modelo:
            return m.size_vram > 0
    return None

In [30]:
x = extrair_letra("Resposta: ** A")
x

'A'

In [ ]:
def perguntar(modelo, prompt):
    r = ollama.chat(
        model=modelo,
        messages=[
            {"role": "system", "content": SYSTEM},
            {"role": "user", "content": prompt},
        ],
        options={"temperature": 0, "seed": 42, "num_ctx": 4096},
        keep_alive="30m",
    )
    texto = r["message"]["content"]
    pct_gpu, tamanho_gb = usou_gpu(modelo)  
    return {
        "resposta_bruta": texto,
        "letra": extrair_letra(texto),
        "tempo_s": r["total_duration"] / 1e9,
        "tokens_prompt": r["prompt_eval_count"],
        "tokens_saida": r["eval_count"],
        "usou_gpu": usou_gpu(modelo),
    }

In [42]:
# escolha o modelo
modelo = "gemma4:e4b-it-q4_K_M"
resultados = []

for _, row in prova_2015.iterrows():
        out = perguntar(modelo, montar_prompt(row))
        resultados.append({"modelo": modelo, "Nquestao": row["Nquestao"], **out})

  
    
df_res = pd.DataFrame(resultados)

In [45]:
df_final = prova_2015.merge(df_res, on="Nquestao", how="left")
df_final["absoluto_correto"] = df_final["letra"] == df_final["gabarito"]
df_final["absoluto_correto"].sum() / len(df_final) * 100

np.float64(30.097087378640776)

In [50]:
df_final.head(50)

,Nquestao,enunciado,A,B,C,D,E,questao_completa,Ano,Aplicacao,gabarito,modelo,resposta_bruta,letra,tempo_s,tokens_prompt,tokens_saida,usou_gpu,absoluto_correto
0,1,"Suponha que, entabulado contrato facultativo d...",O prazo prescricional anual é interrompido com...,O prazo prescricional anual é interrompido com...,O prazo prescricional trienal é suspenso com o...,O prazo prescricional anual é suspenso com o p...,"Na hipótese de resseguro, o prazo prescriciona...","Suponha que, entabulado contrato facultativo d...",2015,2,D,gemma4:e4b-it-q4_K_M,Resposta: A,A,8.245840,376,1126,True,False
1,2,No que se refere ao contrato estimatório do Di...,"Pode ter por objeto bem fungível, e a restitui...","Os riscos são do consignante, que suporta a pe...","Após a entrega da coisa, a posse é exercida em...",O preço de estima é ato unilateral do consigna...,Em decorrência da natureza própria do contrato...,No que se refere ao contrato estimatório do Di...,2015,2,A,gemma4:e4b-it-q4_K_M,Resposta: A,A,5.812732,285,828,True,True
2,2,No que se refere ao contrato estimatório do Di...,"Pode ter por objeto bem fungível, e a restitui...","Os riscos são do consignante, que suporta a pe...","Após a entrega da coisa, a posse é exercida em...",O preço de estima é ato unilateral do consigna...,Em decorrência da natureza própria do contrato...,No que se refere ao contrato estimatório do Di...,2015,2,A,gemma4:e4b-it-q4_K_M,Resposta: A,A,5.832850,285,803,True,True
3,2,No que se refere ao contrato estimatório do Di...,"Pode ter por objeto bem fungível, e a restitui...","Os riscos são do consignante, que suporta a pe...","Após a entrega da coisa, a posse é exercida em...",O preço de estima é ato unilateral do consigna...,Em decorrência da natureza própria do contrato...,No que se refere ao contrato estimatório do Di...,2015,2,C,gemma4:e4b-it-q4_K_M,Resposta: A,A,5.812732,285,828,True,False
4,2,No que se refere ao contrato estimatório do Di...,"Pode ter por objeto bem fungível, e a restitui...","Os riscos são do consignante, que suporta a pe...","Após a entrega da coisa, a posse é exercida em...",O preço de estima é ato unilateral do consigna...,Em decorrência da natureza própria do contrato...,No que se refere ao contrato estimatório do Di...,2015,2,C,gemma4:e4b-it-q4_K_M,Resposta: A,A,5.832850,285,803,True,False
5,3,A respeito da hermenêutica e da aplicação do d...,Diante da existência de antinomia entre dois d...,"Os tradicionais critérios hierárquico, cronoló...",A técnica da subsunção é suficiente e adequada...,Diante da existência de antinomia entre dois d...,"A aplicação do princípio da especialidade, em ...",A respeito da hermenêutica e da aplicação do d...,2015,2,A,gemma4:e4b-it-q4_K_M,Resposta: A,A,7.168110,336,967,True,True
6,4,A respeito da locação dos imóveis urbanos da L...,"Conforme entendimento consolidado do STJ, o pr...",É assente na jurisprudência do STJ que a cláus...,"Nas locações comerciais, exige-se a anuência d...","Conforme entendimento do STF, a penhora de bem...","A responsabilidade dos fiadores, no caso de pr...",A respeito da locação dos imóveis urbanos da L...,2015,2,C,gemma4:e4b-it-q4_K_M,Resposta: C,C,8.473936,386,1177,True,True
7,5,"No que se refere às pessoas, assinale a opção ...",A declaração de ausência é a condição eficient...,"Está consolidado o entendimento, na doutrina e...",Dentre as pessoas jurídicas de direito público...,"Conforme entendimento prevalente do STJ, a dis...",A emancipação voluntária dos pais é ato revogá...,"No que se refere às pessoas, assinale a opção ...",2015,2,D,gemma4:e4b-it-q4_K_M,Resposta: D,D,8.584856,317,1043,True,True
8,6,"Em atenção ao direito das obrigações, assinale...","Se há assunção cumulativa, compreende-se como ...",A multa moratória e a multa compensatória pode...,A obrigação portável (portable) é aquela em qu...,"Na solidariedade passiva, a renúncia e a remis...","Na assunção de dívida, a oposição da exceção d...","Em atenção ao direito das obrigações, assinale...",2015,2,E,gemma4:e4b-it-q4_K_M,Resposta: C,C,7.967595,310,1064,True,False
9,7,"A respeito da responsabilidade civil, assinale...","De acordo com o Código Civil, a possibilidade ...",Se houver concorrência de culpas e danos a amb...,"Nos termos explicitados no Código Civil, a gra...","Segundo a atual orientação do STJ, a reparação...","Conforme jurisprudência prevalente do STJ, a c...","A respeito da responsabilidade civil, assinale...",2015,2,D,gemma4:e4b-it-q4_K_M,Resposta: A,A,9.850018,317,1306,True,False
10,8,A respeito dos contratos regidos pelo Código C...,"Na promessa de fato de terceiro, decorre do tr...","O mandatário não se responsabiliza, ainda que ...","No \ncontrato \nde \nfiança, \na \nsub-rogação...","No que se refere ao contrato preliminar, a out...","A doação remuneratória, tal como a pura, não s...",A respeito dos contratos regidos pelo Código C...,2015,2,D,gemma4:e4b-it-q4_K_M,Resposta: A,A,8.606584,345,1205,True,False
11,9,"Com fundamento na jurisprudência do STJ, assin...",O contrato de união estável pode ter efeitos r...,"Em regra, a pensão alimentícia devida a ex-côn...","Nas ações de interdição não ajuizadas pelo MP,...",Desde que não haja disposição transacional nem...,"As verbas indenizatórias, auxílio-acidente, va...","Com fundamento na jurisprudência do STJ, assin...",2015,2,C,gemma4:e4b-it-q4_K_M,Resposta: D,D,8.090885,336,1102,True,False
12,10,"A respeito da posse e do direito das coisas, a...","propriedade, \nconforme \ndisposição \nlegal, ...",NaN,A resolução da propriedade determinada por cau...,A sentença que reconhece a usucapião tem natur...,"A posse pode ser adquirida por terceiro, sem m...","A respeito da posse e do direito das coisas, a...",2015,2,E,gemma4:e4b-it-q4_K_M,Resposta: D,D,7.929151,226,1063,True,False
13,11,"A propósito do direito das sucessões, com fund...","A herança é considerada um bem divisível, ante...",O filho do autor da herança tem o direito de e...,O cônjuge supérstite pode opor o direito real ...,O testador só poderá dispor de um terço da her...,O cumprimento de legado de coisa que se determ...,"A propósito do direito das sucessões, com fund...",2015,2,B,gemma4:e4b-it-q4_K_M,Resposta: D,D,8.152014,341,1125,True,False
14,12,"Acerca das ações de alimentos, assinale a opçã...",A ação de alimentos não prossegue se o demanda...,"Na ação de alimentos gravídicos, o prazo para ...","A fixação liminar de alimentos gravídicos, em ...",Mesmo com o estabelecimento do regime de guard...,"Na ação de alimentos, existe a isenção legal d...","Acerca das ações de alimentos, assinale a opçã...",2015,2,D,gemma4:e4b-it-q4_K_M,Resposta: C,C,12.104922,349,1539,True,False
15,13,À luz da legislação processual civil e da juri...,Proposta ação de usucapião no foro do domicíli...,A incompetência relativa somente pode ser argu...,"O réu preso não tem capacidade processual, raz...",O curador especial tem legitimidade para propo...,A parte requerida poderá oferecer exceção decl...,À luz da legislação processual civil e da juri...,2015,2,E,gemma4:e4b-it-q4_K_M,Resposta: D,D,8.235136,389,1052,True,False
16,14,Foi ajuizada uma ação de reparação de danos de...,"Ao receber a inicial, o juiz deve obrigatoriam...",A intimação de advogado diverso daquele consta...,"Não era admissível ao réu, no momento processu...",Deve ser observado o procedimento sumário por ...,"Se, à vista do laudo pericial sobre o qual se ...",Foi ajuizada uma ação de reparação de danos de...,2015,2,D,gemma4:e4b-it-q4_K_M,Resposta: E,E,10.544162,629,1404,True,False
17,15,Assinale a opção correta acerca de Estrutura C...,"Para a Teoria Eclética da Ação, desenvolvida p...",O TCU e os tribunais de contas estaduais são ó...,Por ser um órgão externo de controle do Poder ...,"A jurisdição, contenciosa ou voluntária, é una...","Em consonância com a CF, ao impor que a lei nã...",Assinale a opção correta acerca de Estrutura C...,2015,2,A,gemma4:e4b-it-q4_K_M,Resposta: E,E,7.136249,434,975,True,False
18,16,"Com relação à formação, suspensão e extinção d...","Se o réu, em defesa, alegar e comprovar a exis...",Por se tratar de questão prejudicial de mérito...,A suspensão do processo por convenção é faculd...,O processo considera-se formado com a citação ...,Suspende-se o processo quando for oposta impug...,"Com relação à formação, suspensão e extinção d...",2015,2,C,gemma4:e4b-it-q4_K_M,Resposta: E,E,7.306317,467,970,True,False
19,17,"Acerca dos temas resposta do réu, prazos e lit...",A prerrogativa de prazo em dobro para recorrer...,A exceção de incompetência deve ser arguida em...,"Havendo litisconsórcio passivo facultativo, se...","O réu deverá alegar, na contestação, toda a ma...",A reconvenção tem natureza jurídica de lide se...,"Acerca dos temas resposta do réu, prazos e lit...",2015,2,A,gemma4:e4b-it-q4_K_M,Resposta: E,E,9.838276,444,1243,True,False
20,18,No que se refere a formas e princípios da sent...,A sentença extra petita caracteriza-se quando ...,Os motivos que serviram para determinar o alca...,A sentença que julgar improcedente o pedido é ...,A sentença que homologa a transação firmada en...,A decisão terminativa não pode ser fundamentad...,No que se refere a formas e princípios da sent...,2015,2,C,gemma4:e4b-it-q4_K_M,Resposta: B,B,6.470908,257,883,True,False
21,19,"Acerca de liquidação de sentença e execução, a...",A jurisprudência do STJ vem sedimentando o ent...,O termo inicial para a oposição de embargos à ...,O cumprimento de sentença será feito junto aos...,A sentença arbitral não é legalmente considera...,"Com as alterações legislativas realizadas, o c...","Acerca de liquidação de sentença e execução, a...",2015,2,C,gemma4:e4b-it-q4_K_M,Resposta: E,E,6.880953,285,942,True,False
22,20,No que tange a recursos processuais e ação res...,O vício de julgamento decorre da aplicação inc...,"O julgador deve proceder, diretamente, ao exam...",A suspeição fundada do magistrado enseja a pro...,"A aptidão do órgão jurisdicional de conhecer, ...",O terceiro juridicamente interessado não figur...,No que tange a recursos processuais e ação res...,2015,2,D,gemma4:e4b-it-q4_K_M,Resposta: E,E,8.973718,361,1179,True,False
23,21,A respeito do procedimento cautelar e das medi...,"Em ação cautelar preparatória, cabe à parte fo...",A resposta do réu no processo cautelar resume-...,Caso a sentença no pedido principal seja desfa...,"No procedimento cautelar preparatório, o réu é...",Os efeitos da revelia não incidem no rito caut...,A respeito do procedimento cautelar e das medi...,2015,2,C,gemma4:e4b-it-q4_K_M,Resposta: C,C,7.035387,304,945,True,True
24,22,Considerando o entendimento dos tribunais supe...,A multa instituída no art. 475-J do CPC não po...,"A ação de consignação em pagamento, por ter ca...",A realização de registro público dos contratos...,"A conversão, de ofício ou a requerimento das p...","A ação de prestação de contas, no atual regime...",Considerando o entendimento dos tribunais supe...,2015,2,E,gemma4:e4b-it-q4_K_M,Resposta: E,E,8.561415,324,1150,True,True
25,23,Sobre as condutas penalmente tipificadas no ro...,"A conduta consistente em empregar, na reparaçã...","Constitui circunstância agravante, prevista no...","Não deve ser admitida, sob pena de se configur...","Não se admite, no processo dos crimes contra a...",A conduta consistente em deixar de entregar ao...,Sobre as condutas penalmente tipificadas no ro...,2015,2,A,gemma4:e4b-it-q4_K_M,Resposta: E,E,9.976021,379,1251,True,False
26,24,"De acordo com o entendimento adotado, de forma...",A utilização dos dados extraídos dos registros...,Cabe ao órgão responsável pelo cadastro de pro...,"Para a lícita utilização de escore de crédito,...",A inclusão do nome do consumidor em base de da...,"Verificada, ao tempo em que fora realizada, a ...","De acordo com o entendimento adotado, de forma...",2015,2,A,gemma4:e4b-it-q4_K_M,Resposta: C,C,9.493431,588,1289,True,False
27,25,"Fortunato, empresário, proprietário de uma red...","A inversão do ônus da prova, na situação em ex...","Fortunato, no evento em exame, deve ser legalm...",A explosão do vasilhame configura vício do pro...,Em razão de sua condição econômica de comercia...,"No caso em julgamento, para que se possa respo...","Fortunato, empresário, proprietário de uma red...",2015,2,B,gemma4:e4b-it-q4_K_M,Resposta: A,A,10.182807,580,1410,True,False
28,26,A respeito dos institutos jurídicos da prescri...,"Pelo princípio da actio nata, o termo inicial ...",Para as ações de indenização por danos morais ...,"À luz do ordenamento jurídico em vigor, é de c...","A simples reclamação do consumidor, comprovada...","O ajuizamento de ação de indenização, fundada ...",A respeito dos institutos jurídicos da prescri...,2015,2,E,gemma4:e4b-it-q4_K_M,Resposta: D,D,9.938226,543,1302,True,False
29,27,De acordo com as normas que regulam a proteção...,É considerada abusiva a cláusula contratual qu...,É válida a cláusula inserida em contrato de pl...,A diferenciação de preços praticada por lojist...,Não se mostra abusiva a cláusula contratual qu...,"Aplicam-se, na relação entre o franqueador e o...",De acordo com as normas que regulam a proteção...,2015,2,C,gemma4:e4b-it-q4_K_M,Resposta: E,E,8.431163,557,1038,True,False
30,28,A respeito do acesso à Justiça da Infância e d...,Em razão da competência absoluta da Justiça da...,"De acordo com o STJ, o princípio do juízo imed...",As notícias que envolvam a prática de ato infr...,A propositura das ações judiciais da competênc...,A autorização para o exercício de atividades a...,A respeito do acesso à Justiça da Infância e d...,2015,2,B,gemma4:e4b-it-q4_K_M,Resposta: B,B,10.094573,493,1334,True,True
31,29,Considerando que a colocação em família substi...,A ação de guarda proposta por um dos genitores...,A colocação em família substituta admite a tra...,"A adoção é ato personalíssimo. Admite-se, entr...","Em caso de adoção póstuma, nuncupativa ou post...",Aquele que for nomeado tutor por ato de última...,Considerando que a colocação em família substi...,2015,2,E,gemma4:e4b-it-q4_K_M,Resposta: D,D,6.855730,371,943,True,False
32,30,A respeito dos direitos das crianças e dos ado...,Os atos de alienação parental descritos na Lei...,Na mesma linha das diretrizes impostas pelo EC...,O ECA relaciona obrigações que devem ser cumpr...,O regime de capacidade civil gera reflexos no ...,O programa de acolhimento institucional caract...,A respeito dos direitos das crianças e dos ado...,2015,2,B,gemma4:e4b-it-q4_K_M,Resposta: B,B,8.759449,515,1187,True,True
33,31,"De acordo com o CP, constituem hipóteses de ex...",o estrito cumprimento do dever legal e o estad...,a insignificância da lesão e a inexigibilidade...,a legítima defesa putativa e o estrito cumprim...,o estado de necessidade e a coação moral irres...,o exercício regular de direito e a inexigibili...,"De acordo com o CP, constituem hipóteses de ex...",2015,2,A,gemma4:e4b-it-q4_K_M,Resposta: A,A,4.012536,214,610,True,True
34,32,Considerando as orientações legais relativas a...,"Havendo concurso formal de delitos, em que o a...",As agravantes e as atenuantes previstas no CP ...,"No caso de concurso material de delitos, quand...","O agente, condenado por sentença transitada em...","Se, no curso do prazo, o agente cometer novo c...",Considerando as orientações legais relativas a...,2015,2,A,gemma4:e4b-it-q4_K_M,Resposta: E,E,9.997472,486,1380,True,False
35,33,"Carlos, em unidade de desígnios previamente aj...",Carlos responderá pelo delito de furto qualifi...,Carlos responderá pelos delitos de furto simpl...,Bruno responderá pelo delito de dano qualifica...,Se André estivesse com sessenta e cinco anos d...,Se a Caixa Econômica Federal não apresentar qu...,"Carlos, em unidade de desígnios previamente aj...",2015,2,E,gemma4:e4b-it-q4_K_M,Resposta: B,B,15.220123,634,2080,True,False
36,34,"À luz da jurisprudência sumulada do STJ, assin...",Em decorrência do princípio da individualizaçã...,Ainda que a pena-base tenha sido fixada no mín...,Embora seja vedada a utilização de inquéritos ...,É inadmissível a fixação de pena restritiva de...,O número de majorantes referentes ao delito de...,"À luz da jurisprudência sumulada do STJ, assin...",2015,2,D,gemma4:e4b-it-q4_K_M,Resposta: E,E,8.103763,366,1082,True,False
37,35,"A respeito do crime de abuso de autoridade, as...",Em caso de abuso de autoridade cometido por ag...,O sujeito ativo do crime de abuso de autoridad...,"O mesário eleitoral exerce múnus público, moti...",O particular não pode ser sujeito ativo do cri...,As ações penais relativas aos crimes de abuso ...,"A respeito do crime de abuso de autoridade, as...",2015,2,D,gemma4:e4b-it-q4_K_M,Resposta: D,D,11.332140,351,1547,True,True
38,36,"Com fundamento na Lei n.º 11.464/2007, que mod...",O regime integral fechado poderá ser aplicado ...,Como exceção à regra prevista na legislação de...,Os condenados por crimes hediondos ou assemelh...,A Lei dos Crimes Hediondos é especial e possui...,Os requisitos objetivos da Lei n.º 11.464/2007...,"Com fundamento na Lei n.º 11.464/2007, que mod...",2015,2,C,gemma4:e4b-it-q4_K_M,Resposta: E,E,8.370431,533,1180,True,False
39,37,Acerca da Convenção Americana sobre Direitos H...,O preso não será constrangido a executar traba...,"Há previsão, no Pacto de São José da Costa Ric...",A autoridade policial está obrigada a comparec...,A audiência de custódia prevê que a pessoa det...,O devedor de obrigação alimentar e o depositár...,Acerca da Convenção Americana sobre Direitos H...,2015,2,D,gemma4:e4b-it-q4_K_M,Resposta: B,B,8.362212,406,1129,True,False
40,38,A respeito da colaboração premiada prevista na...,o juiz não participará das negociações realiza...,o juiz poderá homologar a proposta de acordo d...,as partes não podem mais se retratar da propos...,o juiz não participará das negociações realiza...,o juiz participará da fase das negociações rea...,A respeito da colaboração premiada prevista na...,2015,2,A,gemma4:e4b-it-q4_K_M,Resposta: A,A,6.494365,553,954,True,True
41,39,"De acordo com as súmulas em vigência do STF, a...",Admite-se continuidade delitiva nos crimes con...,"Os crimes falimentares, por serem tipificados ...",A definição dos crimes de responsabilidade e o...,Ainda que o agente não subtraia bens da vítima...,A conduta de reduzir tributo mediante prestaçã...,"De acordo com as súmulas em vigência do STF, a...",2015,2,D,gemma4:e4b-it-q4_K_M,Resposta: D,D,10.283961,290,1330,True,True
42,40,"A respeito da extinção da punibilidade, assina...",A superveniência de causa relativamente indepe...,O erro sobre elemento constitutivo do tipo leg...,A conduta será culposa quando o agente der cau...,"A extinção da punibilidade de um dos agentes, ...",O agente deixa de responder pelos atos pratica...,"A respeito da extinção da punibilidade, assina...",2015,2,C,gemma4:e4b-it-q4_K_M,Resposta: C,C,8.426160,324,1163,True,True
43,41,No tocante à jurisprudência sumulada pelo STJ ...,A extinção da punibilidade pela prescrição da ...,"Fixada a pena-base no mínimo legal, a decisão,...",A contagem do prazo para a progressão de regim...,A falta grave interrompe o prazo para a obtenç...,A prática de falta grave interrompe o prazo pa...,No tocante à jurisprudência sumulada pelo STJ ...,2015,2,C,gemma4:e4b-it-q4_K_M,Resposta: E,E,8.664455,361,1159,True,False
44,42,"Com relação à aplicação da lei penal, assinale...",As frações de dia são computadas como um dia i...,"O direito penal, quanto ao tempo do crime, con...","A sentença estrangeira, quando a aplicação da ...",Ficam sujeitos à lei brasileira os crimes cont...,Não é aplicável a lei brasileira aos crimes pr...,"Com relação à aplicação da lei penal, assinale...",2015,2,D,gemma4:e4b-it-q4_K_M,Resposta: D,D,7.122667,376,1019,True,True

In [51]:
df_final.to_csv("resultados_prova_2015.csv", index=False)